---
- name: Configure SSH pubkey authentication 
  connection: local
  gather_facts: False
  hosts: mpls
  vars_files:
  - ../cisco-cred

  tasks:

  - name: configure provider
    set_fact:
      provider:
        username: "{{username}}"
        password: "{{password}}"
        host: "{{inventory_hostname}}"

  - name: Configure user 
    ios_config:
      provider: "{{provider}}"
      lines:
      - username marcc priv 15 secret Gr4n74cc35stu_RE!re

  - name: Configure pubkey auth
    ios_config:
      provider: "{{provider}}"
      lines:
      - username marcc
      - key-string
      -  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRexIBrKV1N0iz8ecK19aQe1Vif3ct5MnMCl4U+DsGJUJCQq1b5Rzd4H8GKiXTfkIUC+HQlaJdNsJHkOcGMBsr52Ae4I1\n 
/RExr2/Es35wZosbN9UpQzS0zzkgTiKHp1PGvAeDws+v3FA78MF6PXYNbNT0lhbCLrQTGVSAdrxULIrpPR2ZUUKQB1SzPsjGJVCH2KUMEhK32c35HRLWvVfS20iSSEqX2VTlf1VFAIidGErfWt/SM+QOB2\n 
gb2hyybBgekVyj0yiUNnxLBH/oixTShBCuB1v/eiW2TgV3OpY3PC+LyAvy9yU5bvoWPL86aPACchv91NtaehTcQDeMhu2JR marcc@netmon3-wa"
      - exit
      parents: ip ssh pubkey-chain
