---
- name: modify SNMP_ACL to allow new subnets
  connection: local
  gather_facts: "False"
  hosts: all
  vars_files:
  - ../cisco-cred

  tasks:

  - name: configure provider
    set_fact:
      provider:
        username: "{{username}}"
        password: "{{password}}"
        host: "{{inventory_hostname}}"

  - name: modify the access-list SNMP_ACL
    ios_config:
      provider: "{{provider}}"
      timeout: 60
      lines:
        - no deny any log
        - permit 10.2.0.0 0.0.255.255
        - permit 101.1.0.0 0.0.255.255
        - permit 140.1.0.0 0.0.0.255
        - deny any log
      parents: ip access-list standard SNMP_ACL
      save_when: modified

  - name: apply the access list to the snmp-server
    ios_config:
      provider: "{{provider}}"
      lines:
        - snmp-server community Husco RO SNMP_ACL
      save_when: modified
#
#  - name: save current running configuration
#    ios_config:
#      provider: "{{provider}}"
#      command: wr mem
